// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestWebAPI.Datos;

#nullable disable

namespace TestWebAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240208233046_LlenarVilla")]
    partial class LlenarVilla
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TestWebAPI.Modelos.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagenURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MetrosCuadrados")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ocupantes")
                        .HasColumnType("int");

                    b.Property<double>("Tarifa")
                        .HasColumnType("float");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenidad = "",
                            CreateDate = new DateTime(2024, 2, 8, 17, 30, 46, 615, DateTimeKind.Local).AddTicks(7360),
                            Detalle = "Rustica",
                            ImagenURL = "",
                            MetrosCuadrados = 50,
                            Nombre = "Aldea",
                            Ocupantes = 5,
                            Tarifa = 200.0,
                            UpdateDate = new DateTime(2024, 2, 8, 17, 30, 46, 615, DateTimeKind.Local).AddTicks(7376)
                        },
                        new
                        {
                            Id = 2,
                            Amenidad = "",
                            CreateDate = new DateTime(2024, 2, 8, 17, 30, 46, 615, DateTimeKind.Local).AddTicks(7379),
                            Detalle = "Alto",
                            ImagenURL = "",
                            MetrosCuadrados = 500,
                            Nombre = "Pueblo",
                            Ocupantes = 1,
                            Tarifa = 20.0,
                            UpdateDate = new DateTime(2024, 2, 8, 17, 30, 46, 615, DateTimeKind.Local).AddTicks(7379)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
